//! Function parameter types for Ghidra Rust.
//!
//! Direct translation of `ghidra.program.model.listing.Parameter`.
//!
//! A function parameter is a [`Variable`] with an ordinal position within the
//! function's signature and awareness of auto-parameter conventions.

use crate::data::DataType;
use crate::listing::auto_parameter_type::AutoParameterType;
use crate::listing::variable::VariableData;
use crate::symbol::SourceType;
use std::sync::Arc;

// Re-export AutoParameterType from the auto_parameter_type module.
pub use crate::listing::auto_parameter_type::AutoParameterType as ParameterAutoType;

/// Describes how a function's signature is being updated.
///
/// Corresponds to `Function.FunctionUpdateType`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum FunctionUpdateType {
    /// All parameters and return already have specific storage assigned.
    CustomStorage,
    /// Formal signature params/return specified without storage; storage computed.
    DynamicStorageFormalParams,
    /// All params and return without storage; storage computed with `this` inference.
    DynamicStorageAllParams,
}

/// A function parameter. Extends [`Variable`] with ordinal position and
/// auto-parameter awareness.
///
/// Corresponds to `ghidra.program.model.listing.Parameter`.
#[derive(Debug, Clone)]
pub struct Parameter {
    /// The underlying variable data (name, type, storage, comment).
    pub variable: VariableData,
    /// The ordinal position of this parameter in the function signature
    /// (0 = first parameter, -1 = return).
    pub ordinal: i32,
    /// Whether this parameter was auto-generated by the calling convention
    /// (e.g., `this` pointer, `__return_storage_ptr__`).
    pub auto_parameter: bool,
    /// If auto-parameter, the specific type.
    pub auto_parameter_type: Option<AutoParameterType>,
    /// Whether this parameter was forced to be passed as a pointer (forced indirect).
    pub forced_indirect: bool,
    /// The original formal data type before forced indirect conversion.
    pub formal_data_type: Option<Arc<dyn DataType>>,
}

impl Parameter {
    /// Sentinel ordinal for the return "parameter".
    pub const RETURN_ORDINAL: i32 = -1;
    /// Sentinel ordinal for an unassigned parameter.
    pub const UNASSIGNED_ORDINAL: i32 = -2;
    /// The display name for the return pseudo-parameter.
    pub const RETURN_NAME: &'static str = "<RETURN>";

    /// Create a new parameter.
    pub fn new(
        name: impl Into<String>,
        data_type: Option<Arc<dyn DataType>>,
        ordinal: i32,
        source: SourceType,
    ) -> Self {
        Self {
            variable: VariableData {
                name: Some(name.into()),
                length: data_type.as_ref().map(|dt| dt.get_size()).unwrap_or(0),
                valid: true,
                source,
                comment: None,
                is_stack: false,
                is_register: false,
                is_memory: false,
                is_unique: false,
                stack_offset: None,
                first_storage_address: None,
                first_storage_size: None,
            },
            ordinal,
            auto_parameter: false,
            auto_parameter_type: None,
            forced_indirect: false,
            formal_data_type: data_type,
        }
    }

    /// Create a return parameter.
    pub fn return_param(data_type: Option<Arc<dyn DataType>>) -> Self {
        Self::new(Self::RETURN_NAME, data_type, Self::RETURN_ORDINAL, SourceType::Default)
    }

    /// Builder: set auto-parameter information.
    pub fn with_auto_param(mut self, auto_type: AutoParameterType) -> Self {
        self.auto_parameter = true;
        self.auto_parameter_type = Some(auto_type);
        self
    }

    /// Builder: set forced indirect.
    pub fn with_forced_indirect(mut self, formal_type: Arc<dyn DataType>) -> Self {
        self.forced_indirect = true;
        self.formal_data_type = Some(formal_type);
        self
    }

    /// The parameter name.
    pub fn name(&self) -> Option<&str> {
        use crate::listing::variable::Variable;
        self.variable.get_name()
    }

    /// The data type.
    pub fn data_type(&self) -> Option<&Arc<dyn DataType>> {
        self.formal_data_type.as_ref()
    }

    /// Returns true if this is the return pseudo-parameter.
    pub fn is_return(&self) -> bool {
        self.ordinal == Self::RETURN_ORDINAL
    }

    /// Returns true if this is an auto-parameter.
    pub fn is_auto_parameter(&self) -> bool {
        self.auto_parameter
    }

    /// Returns true if this parameter was forced to indirect (pointer) storage.
    pub fn is_forced_indirect(&self) -> bool {
        self.forced_indirect
    }

    /// The effective data type (the one used for storage, which may be a pointer
    /// if forced indirect).
    pub fn effective_data_type(&self) -> Option<&Arc<dyn DataType>> {
        self.formal_data_type.as_ref()
    }

    /// The formal (original) data type before any forced indirect conversion.
    pub fn formal_data_type(&self) -> Option<&Arc<dyn DataType>> {
        self.formal_data_type.as_ref()
    }
}

impl Default for Parameter {
    fn default() -> Self {
        Self {
            variable: VariableData {
                name: None,
                length: 0,
                valid: false,
                source: SourceType::Default,
                comment: None,
                is_stack: false,
                is_register: false,
                is_memory: false,
                is_unique: false,
                stack_offset: None,
                first_storage_address: None,
                first_storage_size: None,
            },
            ordinal: Self::UNASSIGNED_ORDINAL,
            auto_parameter: false,
            auto_parameter_type: None,
            forced_indirect: false,
            formal_data_type: None,
        }
    }
}

impl PartialEq for Parameter {
    fn eq(&self, other: &Self) -> bool {
        self.ordinal == other.ordinal
            && self.auto_parameter == other.auto_parameter
            && self.forced_indirect == other.forced_indirect
    }
}

impl Eq for Parameter {}

impl std::hash::Hash for Parameter {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.ordinal.hash(state);
        self.auto_parameter.hash(state);
        self.forced_indirect.hash(state);
    }
}

/// Concrete implementation of Parameter (for database-backed use).
pub type ParameterImpl = Parameter;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::listing::variable::VariableData;

    #[test]
    fn test_parameter_creation() {
        let param = Parameter::new("argc", None, 0, SourceType::UserDefined);
        assert_eq!(param.name(), Some("argc"));
        assert_eq!(param.ordinal, 0);
        assert!(!param.is_return());
        assert!(!param.is_auto_parameter());
    }

    #[test]
    fn test_return_parameter() {
        let ret = Parameter::return_param(None);
        assert!(ret.is_return());
        assert_eq!(ret.name(), Some("<RETURN>"));
        assert_eq!(ret.ordinal, Parameter::RETURN_ORDINAL);
    }

    #[test]
    fn test_auto_parameter() {
        let param = Parameter::new("this", None, 0, SourceType::Default)
            .with_auto_param(AutoParameterType::This);
        assert!(param.is_auto_parameter());
        assert_eq!(param.auto_parameter_type, Some(AutoParameterType::This));
    }

    #[test]
    fn test_auto_parameter_display() {
        assert_eq!(format!("{}", AutoParameterType::This), "this");
        assert_eq!(format!("{}", AutoParameterType::ReturnStoragePtr), "__return_storage_ptr__");
    }

    #[test]
    fn test_function_update_type() {
        let t = FunctionUpdateType::CustomStorage;
        assert_eq!(t, FunctionUpdateType::CustomStorage);
        assert_ne!(t, FunctionUpdateType::DynamicStorageAllParams);
    }

    #[test]
    fn test_parameter_default() {
        let param = Parameter::default();
        assert_eq!(param.ordinal, Parameter::UNASSIGNED_ORDINAL);
        assert!(!param.is_return());
    }
}
