//! Plugin tool framework for the Ghidra Project framework.
//!
//! Ports the key Java types from `ghidra.framework.plugintool`:
//! - `Plugin` -- abstract base for all plugins
//! - `PluginTool` -- manages plugins, services, and event routing
//! - `PluginManager` -- manages plugin lifecycle
//! - `PluginEvent` -- events generated by plugins
//! - `PluginInfo`, `PluginDescription` -- plugin metadata
//! - `ServiceInfo`, `ServiceManager` -- service registry
//! - `PluginPackagingProvider`, `PluginConfigurationModel` -- configuration
//! - `ModalPluginTool`, `StandAlonePluginTool` -- tool variants

use std::collections::HashMap;
use std::fmt;
use std::sync::Arc;

use super::ProjectResult;

// ============================================================================
// PluginEvent
// ============================================================================

/// An event generated by a plugin, consumed by other plugins via the tool's
/// event routing system.
///
/// In Java: `ghidra.framework.plugintool.PluginEvent`.
#[derive(Debug, Clone)]
pub struct PluginEvent {
    /// The event type/source name.
    pub event_name: String,
    /// The plugin that generated this event.
    pub source_name: String,
    /// Arbitrary event data (serialized).
    pub data: Option<Vec<u8>>,
    /// Event creation timestamp.
    pub timestamp: u64,
}

impl PluginEvent {
    /// Create a new plugin event.
    pub fn new(
        event_name: impl Into<String>,
        source_name: impl Into<String>,
    ) -> Self {
        static COUNTER: std::sync::atomic::AtomicU64 = std::sync::atomic::AtomicU64::new(0);
        Self {
            event_name: event_name.into(),
            source_name: source_name.into(),
            data: None,
            timestamp: COUNTER.fetch_add(1, std::sync::atomic::Ordering::Relaxed),
        }
    }

    /// Create a plugin event with data.
    pub fn with_data(
        event_name: impl Into<String>,
        source_name: impl Into<String>,
        data: Vec<u8>,
    ) -> Self {
        let mut event = Self::new(event_name, source_name);
        event.data = Some(data);
        event
    }
}

// ============================================================================
// Plugin lifecycle
// ============================================================================

/// Lifecycle phases of a plugin.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PluginLifecycle {
    /// Plugin has been discovered but not yet loaded.
    Discovered,
    /// Plugin class has been loaded into memory.
    Loaded,
    /// Plugin has been initialized.
    Initialized,
    /// Plugin is actively running.
    Running,
    /// Plugin has been stopped / disposed.
    Disposed,
    /// Plugin encountered an error during a lifecycle transition.
    Error,
}

impl PluginLifecycle {
    /// Returns `true` if the plugin is in an active state.
    pub fn is_active(&self) -> bool {
        matches!(self, Self::Initialized | Self::Running)
    }
}

// ============================================================================
// Plugin trait
// ============================================================================

/// Abstract base for all Ghidra plugins.
///
/// In Java: `ghidra.framework.plugintool.Plugin`.
pub trait Plugin: Send + Sync + fmt::Debug {
    /// The unique name of this plugin.
    fn name(&self) -> &str;

    /// A description of this plugin.
    fn description(&self) -> &str;

    /// The current lifecycle phase.
    fn lifecycle(&self) -> PluginLifecycle;

    /// The services this plugin provides.
    fn services_provided(&self) -> Vec<&str> {
        Vec::new()
    }

    /// The services this plugin depends on.
    fn services_required(&self) -> Vec<&str> {
        Vec::new()
    }

    /// The events this plugin consumes.
    fn consumed_events(&self) -> Vec<&str> {
        Vec::new()
    }

    /// The events this plugin produces.
    fn produced_events(&self) -> Vec<&str> {
        Vec::new()
    }

    /// Plugin category.
    fn category(&self) -> Option<&str> {
        None
    }

    /// Called when the plugin is initialized.
    fn init(&mut self) -> ProjectResult<()> {
        Ok(())
    }

    /// Called when the plugin is disposed.
    fn dispose(&mut self) {}

    /// Process a plugin event.
    fn process_event(&mut self, _event: &PluginEvent) {}

    /// Whether this plugin is enabled.
    fn is_enabled(&self) -> bool {
        true
    }

    /// Enable or disable this plugin.
    fn set_enabled(&mut self, _enabled: bool) {}
}

// ============================================================================
// ServiceInfo
// ============================================================================

/// Information about a service provided by a plugin.
///
/// In Java: `ghidra.framework.plugintool.ServiceInfo`.
#[derive(Debug, Clone)]
pub struct ServiceInfo {
    /// The service interface name.
    pub interface_name: String,
    /// The plugin name that provides this service.
    pub provider_name: String,
    /// A description of this service.
    pub description: String,
}

impl ServiceInfo {
    /// Create new service info.
    pub fn new(
        interface_name: impl Into<String>,
        provider_name: impl Into<String>,
        description: impl Into<String>,
    ) -> Self {
        Self {
            interface_name: interface_name.into(),
            provider_name: provider_name.into(),
            description: description.into(),
        }
    }
}

// ============================================================================
// PluginInfo / PluginDescription
// ============================================================================

/// Metadata about a plugin, derived from annotations on the Plugin class.
///
/// In Java: `ghidra.framework.plugintool.PluginInfo` and `PluginDescription`.
#[derive(Debug, Clone)]
pub struct PluginDescription {
    /// Plugin class name.
    pub class_name: String,
    /// Plugin short name.
    pub plugin_name: String,
    /// A brief description.
    pub description: String,
    /// Plugin category.
    pub category: String,
    /// Plugin package name.
    pub package_name: String,
    /// Services this plugin provides.
    pub services_provided: Vec<String>,
    /// Services this plugin requires.
    pub services_required: Vec<String>,
    /// Events consumed.
    pub events_consumed: Vec<String>,
    /// Events produced.
    pub events_produced: Vec<String>,
    /// Plugin priority (load order).
    pub priority: i32,
    /// Whether this plugin is an extension point.
    pub is_extension_point: bool,
}

impl PluginDescription {
    /// Create a new plugin description.
    pub fn new(
        class_name: impl Into<String>,
        plugin_name: impl Into<String>,
        description: impl Into<String>,
    ) -> Self {
        Self {
            class_name: class_name.into(),
            plugin_name: plugin_name.into(),
            description: description.into(),
            category: String::new(),
            package_name: String::new(),
            services_provided: Vec::new(),
            services_required: Vec::new(),
            events_consumed: Vec::new(),
            events_produced: Vec::new(),
            priority: 0,
            is_extension_point: false,
        }
    }
}

impl PartialOrd for PluginDescription {
    fn partial_cmp(&self, other: &Self) -> Option<std::cmp::Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for PluginDescription {
    fn cmp(&self, other: &Self) -> std::cmp::Ordering {
        self.priority.cmp(&other.priority)
    }
}

impl PartialEq for PluginDescription {
    fn eq(&self, other: &Self) -> bool {
        self.class_name == other.class_name
    }
}

impl Eq for PluginDescription {}

// ============================================================================
// ServiceManager
// ============================================================================

/// Manages plugin services.  A plugin may provide a service, or depend on one.
///
/// In Java: `ghidra.framework.plugintool.mgr.ServiceManager`.
#[derive(Debug, Default)]
pub struct ServiceManager {
    /// Maps service interface name -> list of (provider_plugin_name, service_object_id).
    services: HashMap<String, Vec<(String, u64)>>,
    /// Pending notifications.
    notify_add: bool,
    /// Pending service additions (batched until notifications are enabled).
    pending_notifications: Vec<(String, String, u64)>,
}

impl ServiceManager {
    /// Create a new service manager.
    pub fn new() -> Self {
        Self {
            services: HashMap::new(),
            notify_add: true,
            pending_notifications: Vec::new(),
        }
    }

    /// Register a service.
    pub fn add_service(
        &mut self,
        interface_name: impl Into<String>,
        provider_name: impl Into<String>,
        service_id: u64,
    ) {
        let interface = interface_name.into();
        let provider = provider_name.into();
        let list = self
            .services
            .entry(interface.clone())
            .or_insert_with(Vec::new);
        // Prevent duplicate entries.
        if list.iter().any(|(_, sid)| *sid == service_id) {
            return;
        }
        list.push((provider.clone(), service_id));
        if self.notify_add {
            // In a real implementation, this would notify listeners.
        } else {
            self.pending_notifications
                .push((interface, provider, service_id));
        }
    }

    /// Remove a service.
    pub fn remove_service(&mut self, interface_name: &str, service_id: u64) {
        if let Some(list) = self.services.get_mut(interface_name) {
            list.retain(|(_, sid)| *sid != service_id);
            if list.is_empty() {
                self.services.remove(interface_name);
            }
        }
    }

    /// Get all providers for a service interface.
    pub fn get_providers(&self, interface_name: &str) -> Vec<&(String, u64)> {
        self.services
            .get(interface_name)
            .map(|v| v.iter().collect())
            .unwrap_or_default()
    }

    /// Get the first provider for a service interface.
    pub fn get_provider(&self, interface_name: &str) -> Option<&(String, u64)> {
        self.services
            .get(interface_name)
            .and_then(|v| v.first())
    }

    /// Whether a service is registered.
    pub fn has_service(&self, interface_name: &str) -> bool {
        self.services
            .get(interface_name)
            .map(|v| !v.is_empty())
            .unwrap_or(false)
    }

    /// All registered service interface names.
    pub fn service_names(&self) -> Vec<&String> {
        self.services.keys().collect()
    }

    /// Enable/disable service-added notifications.
    pub fn set_notifications_enabled(&mut self, enabled: bool) {
        self.notify_add = enabled;
        if enabled {
            // Flush pending notifications.
            self.pending_notifications.clear();
        }
    }

    /// Number of registered services.
    pub fn service_count(&self) -> usize {
        self.services.values().map(|v| v.len()).sum()
    }
}

// ============================================================================
// PluginManager
// ============================================================================

/// Manages plugin lifecycle for a tool.
///
/// In Java: `ghidra.framework.plugintool.PluginManager`.
#[derive(Debug, Default)]
pub struct PluginManager {
    plugins: Vec<Box<dyn Plugin>>,
    lifecycles: HashMap<String, PluginLifecycle>,
    descriptions: HashMap<String, PluginDescription>,
}

impl PluginManager {
    /// Create a new plugin manager.
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a plugin description (before loading).
    pub fn register_description(&mut self, desc: PluginDescription) {
        self.lifecycles
            .insert(desc.plugin_name.clone(), PluginLifecycle::Discovered);
        self.descriptions
            .insert(desc.plugin_name.clone(), desc);
    }

    /// Get the lifecycle phase for a plugin.
    pub fn get_lifecycle(&self, name: &str) -> Option<&PluginLifecycle> {
        self.lifecycles.get(name)
    }

    /// Get all registered descriptions.
    pub fn descriptions(&self) -> &HashMap<String, PluginDescription> {
        &self.descriptions
    }

    /// Get a plugin by name.
    pub fn get_plugin(&self, name: &str) -> Option<&dyn Plugin> {
        self.plugins.iter().find(|p| p.name() == name).map(|p| p.as_ref())
    }

    /// Number of registered plugins.
    pub fn plugin_count(&self) -> usize {
        self.plugins.len()
    }

    /// All plugin names.
    pub fn plugin_names(&self) -> Vec<&str> {
        self.plugins.iter().map(|p| p.name()).collect()
    }
}

// ============================================================================
// PluginTool (interface)
// ============================================================================

/// The tool that hosts plugins and provides service routing.
///
/// In Java: `ghidra.framework.plugintool.PluginTool`.
pub trait PluginToolInterface: Send + Sync + fmt::Debug {
    /// The name of this tool.
    fn name(&self) -> &str;

    /// Whether the tool is in a busy state.
    fn is_busy(&self) -> bool;

    /// Fire a plugin event.
    fn fire_plugin_event(&self, event: PluginEvent);

    /// Get a service by interface name.
    fn get_service(&self, interface_name: &str) -> Option<u64>;

    /// Whether a service is available.
    fn has_service(&self, interface_name: &str) -> bool;

    /// Get all running tools.
    fn running_tool_count(&self) -> usize;
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_plugin_event() {
        let event = PluginEvent::new("ProgramOpened", "MyPlugin");
        assert_eq!(event.event_name, "ProgramOpened");
        assert_eq!(event.source_name, "MyPlugin");
        assert!(event.data.is_none());

        let event2 = PluginEvent::with_data("DataChanged", "OtherPlugin", vec![1, 2, 3]);
        assert_eq!(event2.data, Some(vec![1, 2, 3]));
    }

    #[test]
    fn test_plugin_lifecycle() {
        assert!(PluginLifecycle::Running.is_active());
        assert!(PluginLifecycle::Initialized.is_active());
        assert!(!PluginLifecycle::Disposed.is_active());
        assert!(!PluginLifecycle::Error.is_active());
        assert!(!PluginLifecycle::Discovered.is_active());
    }

    #[test]
    fn test_service_info() {
        let info = ServiceInfo::new("ProgramService", "ProgramPlugin", "Provides program access");
        assert_eq!(info.interface_name, "ProgramService");
        assert_eq!(info.provider_name, "ProgramPlugin");
    }

    #[test]
    fn test_plugin_description() {
        let desc = PluginDescription::new("MyPlugin", "My Plugin", "Does stuff");
        assert_eq!(desc.class_name, "MyPlugin");
        assert_eq!(desc.plugin_name, "My Plugin");

        let mut desc2 = PluginDescription::new("OtherPlugin", "Other", "More stuff");
        desc2.priority = 5;
        assert!(desc < desc2); // 0 < 5
    }

    #[test]
    fn test_service_manager() {
        let mut mgr = ServiceManager::new();
        assert_eq!(mgr.service_count(), 0);

        mgr.add_service("ProgramService", "Plugin1", 1);
        mgr.add_service("ProgramService", "Plugin2", 2);
        mgr.add_service("ListingService", "Plugin3", 3);

        assert!(mgr.has_service("ProgramService"));
        assert!(mgr.has_service("ListingService"));
        assert!(!mgr.has_service("NonExistent"));
        assert_eq!(mgr.service_count(), 3);

        let providers = mgr.get_providers("ProgramService");
        assert_eq!(providers.len(), 2);

        let first = mgr.get_provider("ProgramService");
        assert!(first.is_some());
        assert_eq!(first.unwrap().0, "Plugin1");

        // Duplicate prevention.
        mgr.add_service("ProgramService", "Plugin1", 1);
        assert_eq!(mgr.service_count(), 3);

        // Remove.
        mgr.remove_service("ProgramService", 1);
        assert_eq!(mgr.service_count(), 2);
        assert!(mgr.get_provider("ProgramService").unwrap().0 == "Plugin2");

        let names: Vec<&String> = mgr.service_names();
        assert_eq!(names.len(), 2);
    }

    #[test]
    fn test_plugin_manager() {
        let mut mgr = PluginManager::new();
        assert_eq!(mgr.plugin_count(), 0);

        let desc = PluginDescription::new("TestPlugin", "Test Plugin", "A test plugin");
        mgr.register_description(desc);
        assert!(mgr.get_lifecycle("Test Plugin").is_some());
        assert_eq!(
            mgr.get_lifecycle("Test Plugin"),
            Some(&PluginLifecycle::Discovered)
        );
        assert_eq!(mgr.descriptions().len(), 1);
    }
}
