//! Data type merge support.
//!
//! Ports Ghidra's `DataTypeMerger`, `EnumMerger`, `StructureMerger`,
//! `UnionMerger`, and `DataTypeMergeException`.

mod enum_merger;
mod structure_merger;
mod union_merger;

pub use enum_merger::EnumMerger;
pub use structure_merger::StructureMerger;
pub use union_merger::UnionMerger;

use crate::base::merge::error::{DataTypeMergeError, MergeResult};

/// A component of a composite data type (struct field or union member).
///
/// Port of Ghidra's `DataTypeComponent`.
#[derive(Debug, Clone)]
pub struct MergeDataTypeComponent {
    /// The ordinal position within the composite.
    pub ordinal: usize,
    /// The byte offset of this component within the composite.
    pub offset: usize,
    /// The length of this component in bytes.
    pub length: usize,
    /// The name of this field (may be `None` for anonymous fields).
    pub field_name: Option<String>,
    /// The data type name of this component.
    pub data_type_name: String,
    /// Comment associated with this component.
    pub comment: Option<String>,
}

impl MergeDataTypeComponent {
    /// Create a new component descriptor.
    pub fn new(
        ordinal: usize,
        offset: usize,
        length: usize,
        field_name: Option<String>,
        data_type_name: impl Into<String>,
        comment: Option<String>,
    ) -> Self {
        Self {
            ordinal,
            offset,
            length,
            field_name,
            data_type_name: data_type_name.into(),
            comment,
        }
    }
}

/// An enum value entry: `(name, value, comment)`.
#[derive(Debug, Clone)]
pub struct EnumEntry {
    /// The name of this enum constant.
    pub name: String,
    /// The numeric value.
    pub value: i64,
    /// Optional comment.
    pub comment: Option<String>,
}

impl EnumEntry {
    /// Create a new enum entry.
    pub fn new(name: impl Into<String>, value: i64, comment: Option<String>) -> Self {
        Self {
            name: name.into(),
            value,
            comment,
        }
    }
}

/// A merged data type result produced by a merger.
#[derive(Debug, Clone)]
pub struct MergedDataType {
    /// The name of the merged type.
    pub name: String,
    /// The category path.
    pub category_path: String,
    /// The description of the merged type.
    pub description: Option<String>,
    /// Components of the merged composite (for struct/union).
    pub components: Vec<MergeDataTypeComponent>,
    /// Enum entries (for enum types).
    pub enum_entries: Vec<EnumEntry>,
    /// Size in bytes.
    pub size: usize,
    /// Whether packing is enabled (for structures).
    pub packing_enabled: bool,
    /// Warnings generated during merge.
    pub warnings: Vec<String>,
}

impl MergedDataType {
    /// Create a new merged data type with defaults.
    pub fn new(name: impl Into<String>, size: usize) -> Self {
        Self {
            name: name.into(),
            category_path: "/".to_string(),
            description: None,
            components: Vec::new(),
            enum_entries: Vec::new(),
            size,
            packing_enabled: false,
            warnings: Vec::new(),
        }
    }
}

// ============================================================================
// DataTypeMerger<T> -- generic base trait
// ============================================================================

/// Trait for data type mergers.
///
/// Each merger handles a specific data type kind (enum, structure, union)
/// and implements the `do_merge` method to combine two versions.
pub trait DataTypeMerger {
    /// Merge two data types into a new one.
    ///
    /// Returns the merged data type or a [`DataTypeMergeError`] if a conflict
    /// cannot be resolved automatically.
    fn merge(&mut self) -> MergeResult<MergedDataType>;

    /// Return any warnings generated by the most recent merge.
    fn warnings(&self) -> &[String];
}

/// Join two comment strings, preferring non-blank and appending if different.
pub fn join_comments(comment1: Option<&str>, comment2: Option<&str>) -> Option<String> {
    match (comment1, comment2) {
        (None, None) => None,
        (Some(c), None) => Some(c.to_string()),
        (None, Some(c)) => Some(c.to_string()),
        (Some(a), Some(b)) => {
            if a == b {
                Some(a.to_string())
            } else {
                Some(format!("{} {}", a, b))
            }
        }
    }
}

/// Check if a data type is considered "undefined" (a placeholder).
pub fn is_undefined_type(type_name: &str) -> bool {
    matches!(
        type_name,
        "undefined" | "Undefined" | "undefined1" | "undefined2" | "undefined4" | "undefined8"
    )
}

/// Check if a data type can be "upgraded" to another during merge.
///
/// In Ghidra's model, undefined types and integer types can often be upgraded
/// to more specific types of the same size (e.g., undefined -> pointer,
/// integer -> pointer).
pub fn can_upgrade(from_type: &str, to_type: &str, from_size: usize, to_size: usize) -> bool {
    if from_size != to_size {
        return false;
    }
    // Undefined types can always be upgraded.
    if is_undefined_type(from_type) {
        return true;
    }
    // Integer types can be upgraded to pointer types.
    let is_integer = matches!(
        from_type,
        "int" | "uint" | "dword" | "word" | "byte" | "qword"
            | "SignedByte" | "SignedWord" | "SignedDWord" | "SignedQWord"
            | "UnsignedByte" | "UnsignedWord" | "UnsignedDWord" | "UnsignedQWord"
    );
    let is_pointer = to_type.contains("Pointer") || to_type == "pointer";
    if is_integer && is_pointer {
        return true;
    }
    false
}

/// Pick the best type for merging two conflicting types.
///
/// Returns `Some(type_name)` if one can be upgraded to the other,
/// or `None` if they are incompatible.
pub fn pick_best_type_for_merge(
    type1_name: &str,
    type1_size: usize,
    type2_name: &str,
    type2_size: usize,
) -> Option<String> {
    if type1_size != type2_size {
        return None;
    }
    if can_upgrade(type1_name, type2_name, type1_size, type2_size) {
        Some(type2_name.to_string())
    } else if can_upgrade(type2_name, type1_name, type2_size, type1_size) {
        Some(type1_name.to_string())
    } else {
        None
    }
}

/// Helper: create a `DataTypeMergeError`.
pub fn merge_error(message: impl Into<String>) -> DataTypeMergeError {
    DataTypeMergeError::new(message)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_join_comments_both_none() {
        assert_eq!(join_comments(None, None), None);
    }

    #[test]
    fn test_join_comments_one_none() {
        assert_eq!(
            join_comments(Some("hello"), None),
            Some("hello".to_string())
        );
        assert_eq!(
            join_comments(None, Some("world")),
            Some("world".to_string())
        );
    }

    #[test]
    fn test_join_comments_same() {
        assert_eq!(
            join_comments(Some("same"), Some("same")),
            Some("same".to_string())
        );
    }

    #[test]
    fn test_join_comments_different() {
        assert_eq!(
            join_comments(Some("a"), Some("b")),
            Some("a b".to_string())
        );
    }

    #[test]
    fn test_is_undefined_type() {
        assert!(is_undefined_type("undefined"));
        assert!(is_undefined_type("Undefined"));
        assert!(is_undefined_type("undefined4"));
        assert!(!is_undefined_type("int"));
    }

    #[test]
    fn test_can_upgrade_undefined() {
        assert!(can_upgrade("undefined", "pointer", 4, 4));
        assert!(!can_upgrade("undefined", "pointer", 4, 8));
    }

    #[test]
    fn test_can_upgrade_integer_to_pointer() {
        assert!(can_upgrade("dword", "Pointer32", 4, 4));
        assert!(can_upgrade("int", "Pointer32", 4, 4));
    }

    #[test]
    fn test_pick_best_type_for_merge_same_size() {
        assert_eq!(
            pick_best_type_for_merge("undefined4", 4, "dword", 4),
            Some("dword".to_string())
        );
    }

    #[test]
    fn test_pick_best_type_for_merge_different_size() {
        assert_eq!(pick_best_type_for_merge("int", 4, "int", 8), None);
    }

    #[test]
    fn test_pick_best_type_for_merge_incompatible() {
        assert_eq!(pick_best_type_for_merge("float", 4, "dword", 4), None);
    }

    #[test]
    fn test_data_type_component() {
        let comp = MergeDataTypeComponent::new(
            0,
            0,
            4,
            Some("field_x".to_string()),
            "int",
            Some("a comment".to_string()),
        );
        assert_eq!(comp.ordinal, 0);
        assert_eq!(comp.offset, 0);
        assert_eq!(comp.length, 4);
        assert_eq!(comp.field_name.as_deref(), Some("field_x"));
        assert_eq!(comp.data_type_name, "int");
    }

    #[test]
    fn test_enum_entry() {
        let entry = EnumEntry::new("VALUE_A", 1, None);
        assert_eq!(entry.name, "VALUE_A");
        assert_eq!(entry.value, 1);
    }

    #[test]
    fn test_merged_data_type() {
        let dt = MergedDataType::new("my_struct", 16);
        assert_eq!(dt.name, "my_struct");
        assert_eq!(dt.size, 16);
        assert!(dt.components.is_empty());
        assert!(dt.warnings.is_empty());
    }
}
