//! Database-backed VTMatchSet.

use crate::versiontracking::match_set::VtMatch;
use crate::versiontracking::types::VtAssociationType;

/// Database-backed match set.
///
/// Represents a set of matches generated by a single correlator run.
#[derive(Debug, Clone)]
pub struct VtMatchSetDB {
    /// Database key
    pub id: i64,
    /// Correlator name
    pub correlator_name: String,
    /// Correlator description
    pub correlator_description: String,
    /// Source address set (serialized)
    pub source_address_set: String,
    /// Destination address set (serialized)
    pub destination_address_set: String,
    /// Options XML
    pub options_xml: String,
    /// In-memory match storage
    matches: Vec<VtMatch>,
    /// Next match ID
    next_match_id: u64,
}

impl VtMatchSetDB {
    /// Create a new match set DB record.
    pub fn new(id: i64, correlator_name: &str) -> Self {
        Self {
            id,
            correlator_name: correlator_name.to_string(),
            correlator_description: String::new(),
            source_address_set: String::new(),
            destination_address_set: String::new(),
            options_xml: String::new(),
            matches: Vec::new(),
            next_match_id: 1,
        }
    }

    /// Set the correlator description.
    pub fn set_correlator_description(&mut self, desc: impl Into<String>) {
        self.correlator_description = desc.into();
    }

    /// Set the source address set (serialized form).
    pub fn set_source_address_set(&mut self, set: impl Into<String>) {
        self.source_address_set = set.into();
    }

    /// Set the destination address set (serialized form).
    pub fn set_destination_address_set(&mut self, set: impl Into<String>) {
        self.destination_address_set = set.into();
    }

    /// Set options XML.
    pub fn set_options_xml(&mut self, xml: impl Into<String>) {
        self.options_xml = xml.into();
    }

    /// Add a match to this set.
    pub fn add_match(&mut self, mut vt_match: VtMatch) -> u64 {
        let match_id = self.next_match_id;
        self.next_match_id += 1;
        vt_match.match_set_id = self.id as u64;
        self.matches.push(vt_match);
        match_id
    }

    /// Get a match by index.
    pub fn get_match(&self, index: usize) -> Option<&VtMatch> {
        self.matches.get(index)
    }

    /// Get all matches.
    pub fn get_matches(&self) -> &[VtMatch] {
        &self.matches
    }

    /// Get matches sorted by score (descending).
    pub fn get_matches_by_score(&self) -> Vec<&VtMatch> {
        let mut m: Vec<&VtMatch> = self.matches.iter().collect();
        m.sort_by(|a, b| b.similarity_score.cmp(&a.similarity_score));
        m
    }

    /// Match count.
    pub fn match_count(&self) -> usize {
        self.matches.len()
    }

    /// Delete a match by index.
    pub fn delete_match(&mut self, index: usize) -> bool {
        if index < self.matches.len() {
            self.matches.remove(index);
            true
        } else {
            false
        }
    }

    /// Get matches for a specific association type.
    pub fn get_matches_for_type(&self, assoc_type: VtAssociationType) -> Vec<&VtMatch> {
        self.matches
            .iter()
            .filter(|m| m.association_type == assoc_type)
            .collect()
    }

    /// Get matches for a specific association ID.
    pub fn get_matches_for_association(&self, association_id: u64) -> Vec<&VtMatch> {
        self.matches
            .iter()
            .filter(|m| m.association_id == association_id)
            .collect()
    }

    /// Clear all matches.
    pub fn clear(&mut self) {
        self.matches.clear();
    }

    /// Whether this match set is empty.
    pub fn is_empty(&self) -> bool {
        self.matches.is_empty()
    }

    /// Get the highest confidence match.
    pub fn best_match(&self) -> Option<&VtMatch> {
        self.matches
            .iter()
            .max_by(|a, b| a.confidence_score.cmp(&b.confidence_score))
    }

    /// Get average similarity score.
    pub fn average_similarity(&self) -> f64 {
        if self.matches.is_empty() {
            return 0.0;
        }
        let sum: f64 = self.matches.iter().map(|m| m.similarity_score.score()).sum();
        sum / self.matches.len() as f64
    }

    /// Get average confidence score.
    pub fn average_confidence(&self) -> f64 {
        if self.matches.is_empty() {
            return 0.0;
        }
        let sum: f64 = self.matches.iter().map(|m| m.confidence_score.score()).sum();
        sum / self.matches.len() as f64
    }
}

impl std::fmt::Display for VtMatchSetDB {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "MatchSetDB({}: {} matches)",
            self.correlator_name,
            self.matches.len()
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::versiontracking::types::VtScore;
    use ghidra_core::addr::Address;

    fn make_match(src: u64, dst: u64, sim: f64) -> VtMatch {
        VtMatch {
            association_id: 0,
            match_set_id: 0,
            source_address: Address::new(src),
            destination_address: Address::new(dst),
            association_type: VtAssociationType::Function,
            similarity_score: VtScore::new(sim),
            confidence_score: VtScore::new(sim * 0.9),
            source_length: 100,
            destination_length: 100,
            length_type: "bytes".to_string(),
            tag: crate::versiontracking::types::VtMatchTag::untagged(),
        }
    }

    #[test]
    fn test_match_set_db_create() {
        let ms = VtMatchSetDB::new(1, "TestCorrelator");
        assert_eq!(ms.id, 1);
        assert_eq!(ms.correlator_name, "TestCorrelator");
        assert!(ms.is_empty());
    }

    #[test]
    fn test_match_set_db_add_matches() {
        let mut ms = VtMatchSetDB::new(1, "Test");
        ms.add_match(make_match(0x1000, 0x2000, 0.95));
        ms.add_match(make_match(0x1100, 0x2100, 0.80));
        assert_eq!(ms.match_count(), 2);
    }

    #[test]
    fn test_match_set_db_sorted_by_score() {
        let mut ms = VtMatchSetDB::new(1, "Test");
        ms.add_match(make_match(0x1000, 0x2000, 0.80));
        ms.add_match(make_match(0x1100, 0x2100, 0.95));
        ms.add_match(make_match(0x1200, 0x2200, 0.50));
        let sorted = ms.get_matches_by_score();
        assert!((sorted[0].similarity_score.score() - 0.95).abs() < 0.01);
        assert!((sorted[1].similarity_score.score() - 0.80).abs() < 0.01);
        assert!((sorted[2].similarity_score.score() - 0.50).abs() < 0.01);
    }

    #[test]
    fn test_match_set_db_delete_match() {
        let mut ms = VtMatchSetDB::new(1, "Test");
        ms.add_match(make_match(0x1000, 0x2000, 0.95));
        ms.add_match(make_match(0x1100, 0x2100, 0.80));
        assert!(ms.delete_match(0));
        assert_eq!(ms.match_count(), 1);
        assert!(!ms.delete_match(5));
    }

    #[test]
    fn test_match_set_db_best_match() {
        let mut ms = VtMatchSetDB::new(1, "Test");
        ms.add_match(make_match(0x1000, 0x2000, 0.80));
        ms.add_match(make_match(0x1100, 0x2100, 0.95));
        let best = ms.best_match().unwrap();
        assert!((best.confidence_score.score() - 0.855).abs() < 0.01);
    }

    #[test]
    fn test_match_set_db_averages() {
        let mut ms = VtMatchSetDB::new(1, "Test");
        ms.add_match(make_match(0x1000, 0x2000, 0.80));
        ms.add_match(make_match(0x1100, 0x2100, 1.00));
        assert!((ms.average_similarity() - 0.90).abs() < 0.01);
        assert!((ms.average_confidence() - 0.81).abs() < 0.01);
    }

    #[test]
    fn test_match_set_db_display() {
        let ms = VtMatchSetDB::new(1, "TestCorrelator");
        assert_eq!(format!("{}", ms), "MatchSetDB(TestCorrelator: 0 matches)");
    }
}
