//! Terminal output callback and response encoder.
//!
//! Ported from Ghidra's `VtOutput.java` and `VtResponseEncoder.java`.
//!
//! - [`VtOutput`] -- callback trait for bytes generated by the terminal
//! - [`VtResponseEncoder`] -- encodes terminal response sequences (cursor
//!   position reports, paste bracketing, device status replies)
//! - [`DefaultResponseEncoder`] -- concrete encoder that buffers and emits

/// Callback for bytes generated by the terminal.
///
/// When the terminal needs to send data back (e.g., to report cursor
/// position or acknowledge a device status query), it invokes this
/// trait.  In a real deployment the implementation would write the
/// bytes to a pty or connection stream.
///
/// Ported from `ghidra.app.plugin.core.terminal.vt.VtOutput`.
pub trait VtOutput: Send {
    /// Handle output bytes from the terminal.
    fn out(&mut self, buf: &[u8]);
}

/// A collecting `VtOutput` that appends bytes into an internal buffer.
///
/// Useful for testing.
#[derive(Debug, Default)]
pub struct CollectingOutput {
    /// Accumulated output bytes.
    pub bytes: Vec<u8>,
}

impl CollectingOutput {
    /// Create a new empty collector.
    pub fn new() -> Self {
        Self::default()
    }

    /// Consume the collector and return the accumulated bytes.
    pub fn into_bytes(self) -> Vec<u8> {
        self.bytes
    }

    /// Drain the accumulated bytes, returning them and resetting the buffer.
    pub fn drain(&mut self) -> Vec<u8> {
        std::mem::take(&mut self.bytes)
    }

    /// Interpret accumulated bytes as a UTF-8 string (lossy).
    pub fn to_string_lossy(&self) -> String {
        String::from_utf8_lossy(&self.bytes).into_owned()
    }
}

impl VtOutput for CollectingOutput {
    fn out(&mut self, buf: &[u8]) {
        self.bytes.extend_from_slice(buf);
    }
}

// ---------------------------------------------------------------------------
// VtResponseEncoder
// ---------------------------------------------------------------------------

/// Encodes terminal response sequences.
///
/// When the terminal receives certain queries (e.g., device status report,
/// cursor position request), it must respond with an escape sequence.
/// This encoder produces those sequences.
///
/// Ported from `ghidra.app.plugin.core.terminal.vt.VtResponseEncoder`.
pub trait VtResponseEncoder {
    /// Report the current cursor position to the host.
    ///
    /// Generates: `ESC [ <row> ; <col> R`
    fn report_cursor_pos(&mut self, row: u16, col: u16);

    /// Report the start of a bracketed paste.
    ///
    /// Generates: `ESC [ 200 ~`
    fn report_paste_start(&mut self);

    /// Report the end of a bracketed paste.
    ///
    /// Generates: `ESC [ 201 ~`
    fn report_paste_end(&mut self);

    /// Report device status OK.
    ///
    /// Generates: `ESC [ 0 n`
    fn report_device_status_ok(&mut self);

    /// Report device status malfunction.
    ///
    /// Generates: `ESC [ 3 n`
    fn report_device_status_malfunction(&mut self);

    /// Report terminal identity.
    ///
    /// Generates: `ESC [ ? 1 ; 2 c`  (VT100 with Advanced Video Option)
    fn report_terminal_identity(&mut self);
}

/// The byte sequence that begins a bracketed paste.
pub const PASTE_START: &[u8] = b"\x1b[200~";

/// The byte sequence that ends a bracketed paste.
pub const PASTE_END: &[u8] = b"\x1b[201~";

// ---------------------------------------------------------------------------
// DefaultResponseEncoder
// ---------------------------------------------------------------------------

/// A default response encoder that writes encoded bytes into an `VtOutput`.
///
/// Ported from the abstract `VtResponseEncoder` class in Ghidra.
#[derive(Debug)]
pub struct DefaultResponseEncoder {
    /// Buffer for building response sequences.
    buf: Vec<u8>,
}

impl DefaultResponseEncoder {
    /// Create a new encoder.
    pub fn new() -> Self {
        Self {
            buf: Vec::with_capacity(32),
        }
    }

    /// Flush the internal buffer into the given output.
    fn flush(&mut self, output: &mut dyn VtOutput) {
        if !self.buf.is_empty() {
            output.out(&self.buf);
            self.buf.clear();
        }
    }

    /// Write a cursor position report into the buffer: `ESC [ <row> ; <col> R`.
    fn encode_cursor_pos(&mut self, row: u16, col: u16) {
        self.buf.extend_from_slice(b"\x1b[");
        let s = format!("{};{}", row, col);
        self.buf.extend_from_slice(s.as_bytes());
        self.buf.push(b'R');
    }
}

impl Default for DefaultResponseEncoder {
    fn default() -> Self {
        Self::new()
    }
}

/// A response encoder that writes to a `VtOutput` callback.
pub struct EncoderWithOutput<'a> {
    encoder: DefaultResponseEncoder,
    output: &'a mut dyn VtOutput,
}

impl<'a> EncoderWithOutput<'a> {
    /// Create a new encoder that writes to the given output.
    pub fn new(output: &'a mut dyn VtOutput) -> Self {
        Self {
            encoder: DefaultResponseEncoder::new(),
            output,
        }
    }
}

impl<'a> VtResponseEncoder for EncoderWithOutput<'a> {
    fn report_cursor_pos(&mut self, row: u16, col: u16) {
        self.encoder.encode_cursor_pos(row, col);
        self.encoder.flush(self.output);
    }

    fn report_paste_start(&mut self) {
        self.encoder.buf.extend_from_slice(PASTE_START);
        self.encoder.flush(self.output);
    }

    fn report_paste_end(&mut self) {
        self.encoder.buf.extend_from_slice(PASTE_END);
        self.encoder.flush(self.output);
    }

    fn report_device_status_ok(&mut self) {
        self.encoder.buf.extend_from_slice(b"\x1b[0n");
        self.encoder.flush(self.output);
    }

    fn report_device_status_malfunction(&mut self) {
        self.encoder.buf.extend_from_slice(b"\x1b[3n");
        self.encoder.flush(self.output);
    }

    fn report_terminal_identity(&mut self) {
        self.encoder.buf.extend_from_slice(b"\x1b[?1;2c");
        self.encoder.flush(self.output);
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_collecting_output() {
        let mut out = CollectingOutput::new();
        out.out(b"hello");
        out.out(b" world");
        assert_eq!(out.to_string_lossy(), "hello world");
    }

    #[test]
    fn test_collecting_output_drain() {
        let mut out = CollectingOutput::new();
        out.out(b"abc");
        let bytes = out.drain();
        assert_eq!(bytes, b"abc");
        assert!(out.bytes.is_empty());
    }

    #[test]
    fn test_collecting_output_into_bytes() {
        let mut out = CollectingOutput::new();
        out.out(b"\x1b[5;10R");
        let bytes = out.into_bytes();
        assert_eq!(bytes, b"\x1b[5;10R");
    }

    #[test]
    fn test_encoder_cursor_pos() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_cursor_pos(5, 10);
        }
        assert_eq!(out.bytes, b"\x1b[5;10R");
    }

    #[test]
    fn test_encoder_paste_start() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_paste_start();
        }
        assert_eq!(out.bytes, PASTE_START);
    }

    #[test]
    fn test_encoder_paste_end() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_paste_end();
        }
        assert_eq!(out.bytes, PASTE_END);
    }

    #[test]
    fn test_encoder_device_status_ok() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_device_status_ok();
        }
        assert_eq!(out.bytes, b"\x1b[0n");
    }

    #[test]
    fn test_encoder_device_status_malfunction() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_device_status_malfunction();
        }
        assert_eq!(out.bytes, b"\x1b[3n");
    }

    #[test]
    fn test_encoder_terminal_identity() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_terminal_identity();
        }
        assert_eq!(out.bytes, b"\x1b[?1;2c");
    }

    #[test]
    fn test_encoder_multiple_sequences() {
        let mut out = CollectingOutput::new();
        {
            let mut enc = EncoderWithOutput::new(&mut out);
            enc.report_cursor_pos(1, 1);
            enc.report_paste_start();
            enc.report_paste_end();
        }
        let expected: Vec<u8> = b"\x1b[1;1R\x1b[200~\x1b[201~"
            .iter()
            .copied()
            .collect();
        assert_eq!(out.bytes, expected);
    }

    #[test]
    fn test_paste_start_constant() {
        assert_eq!(PASTE_START, b"\x1b[200~");
    }

    #[test]
    fn test_paste_end_constant() {
        assert_eq!(PASTE_END, b"\x1b[201~");
    }
}
