//! Misc constant values for Go language support, ported from Ghidra's
//! `ghidra.app.util.bin.format.golang.GoConstants`.
//!
//! Provides category paths, calling convention names, and other Go-specific
//! string constants used throughout the Go binary analysis pipeline.

/// Category path for placing Go types in a Ghidra data type manager.
pub const GOLANG_CATEGORYPATH: &str = "/golang";

/// Category path for recovered Go types.
pub const GOLANG_RECOVERED_TYPES_CATEGORYPATH: &str = "/golang-recovered";

/// Calling convention name for Go's `abi-internal` ABI.
pub const GOLANG_ABI_INTERNAL_CALLINGCONVENTION_NAME: &str = "abi-internal";

/// Calling convention name for Go's `abi0` ABI.
pub const GOLANG_ABI0_CALLINGCONVENTION_NAME: &str = "abi0";

/// Calling convention name for `duffzero` zeroing routine.
pub const GOLANG_DUFFZERO_CALLINGCONVENTION_NAME: &str = "duffzero";

/// Calling convention name for `duffcopy` copying routine.
pub const GOLANG_DUFFCOPY_CALLINGCONVENTION_NAME: &str = "duffcopy";

/// Filename used for auto-generated Go code.
pub const GOLANG_AUTOGENERATED_FILENAME: &str = "<autogenerated>";

// ---------------------------------------------------------------------------
// gcWriteBarrier constants
// ---------------------------------------------------------------------------

/// Calling convention name for the initial `gcWriteBarrier` scheme
/// (`func gcWriteBarrier(val, dest)`), used in Go versions before 1.21.
pub const GOLANG_GCWRITE_BUFFERED_CALLINGCONVENTION_NAME: &str = "gcwrite_buffered";

/// Calling convention name for the batch `gcWriteBarrier` scheme
/// (`func gcWriteBarrier[1-8]() uintptr`), used in Go 1.21+.
pub const GOLANG_GCWRITE_BATCH_CALLINGCONVENTION_NAME: &str = "gcwrite_batch";

/// Registers used by the buffered gcWriteBarrier on x86-64 (Go's names).
pub const GCWRITE_BUFFERED_X86_64_REGS: &[&str] = &[
    "CX", "DX", "BX", "BP", "SI", "R8", "R9",
];

// ---------------------------------------------------------------------------
// Parameter names
// ---------------------------------------------------------------------------

/// Name used for the receiver/self parameter in Go method calls.
pub const GOLANG_RECEIVER_PARAM_NAME: &str = "self";

/// Name used for the generics dictionary parameter in Go generic functions.
pub const GOLANG_GENERICS_PARAM_NAME: &str = "generics_dict";

/// Name used for the closure context parameter.
pub const GOLANG_CLOSURE_CONTEXT_NAME: &str = ".context";

/// Go compiler specification name.
pub const GOLANG_CSPEC_NAME: &str = "golang";

// ---------------------------------------------------------------------------
// Go version range markers for gcWriteBarrier schemes
// ---------------------------------------------------------------------------

/// Go versions that use the initial buffered gcWriteBarrier (up to 1.20).
pub const GCWRITE_BUFFERED_MAX_VERSION: (u32, u32) = (1, 20);

/// Go versions that use the batch gcWriteBarrier (1.21+).
pub const GCWRITE_BATCH_MIN_VERSION: (u32, u32) = (1, 21);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_category_paths() {
        assert_eq!(GOLANG_CATEGORYPATH, "/golang");
        assert_eq!(GOLANG_RECOVERED_TYPES_CATEGORYPATH, "/golang-recovered");
    }

    #[test]
    fn test_calling_convention_names() {
        assert_eq!(GOLANG_ABI_INTERNAL_CALLINGCONVENTION_NAME, "abi-internal");
        assert_eq!(GOLANG_ABI0_CALLINGCONVENTION_NAME, "abi0");
        assert_eq!(GOLANG_DUFFZERO_CALLINGCONVENTION_NAME, "duffzero");
        assert_eq!(GOLANG_DUFFCOPY_CALLINGCONVENTION_NAME, "duffcopy");
    }

    #[test]
    fn test_gcwrite_buffered_regs() {
        assert_eq!(GCWRITE_BUFFERED_X86_64_REGS.len(), 7);
        assert_eq!(GCWRITE_BUFFERED_X86_64_REGS[0], "CX");
        assert_eq!(GCWRITE_BUFFERED_X86_64_REGS[6], "R9");
    }

    #[test]
    fn test_parameter_names() {
        assert_eq!(GOLANG_RECEIVER_PARAM_NAME, "self");
        assert_eq!(GOLANG_GENERICS_PARAM_NAME, "generics_dict");
        assert_eq!(GOLANG_CLOSURE_CONTEXT_NAME, ".context");
    }

    #[test]
    fn test_version_ranges() {
        assert_eq!(GCWRITE_BUFFERED_MAX_VERSION, (1, 20));
        assert_eq!(GCWRITE_BATCH_MIN_VERSION, (1, 21));
    }
}
