//! Data-flow and control-flow analysis transforms.
//!
//! This module contains the decompiler analysis pipeline:
//! 1. **CFG construction** ([`cfg`]) -- build control-flow graph from P-code
//! 2. **SSA form** ([`ssa`]) -- static single assignment construction
//! 3. **Data-flow analysis** ([`dataflow`]) -- reaching definitions, ranges, constants
//! 4. **Expression simplification** ([`simplify`]) -- constant folding, algebraic identities
//! 5. **C output generation** ([`output`]) -- formatted C source from structured IR
//!
//! Also included:
//! - **Control-flow structuring** ([`control_flow_struct`]) -- region-based loop/if/switch detection
//! - **C output formatter** ([`c_output`]) -- structured node to C text
//! - **Data-flow engine** ([`dataflow_engine`]) -- varnode-level def-use analysis
//! - **Type recovery** ([`type_recovery`]) -- constraint-based type inference

pub mod c_output;
pub mod cfg;
pub mod control_flow_struct;
pub mod dataflow;
pub mod dataflow_engine;
pub mod output;
pub mod simplify;
pub mod ssa;
pub mod type_recovery;

use std::collections::HashMap;
use ghidra_core::error::Result as GhidraResult;
use crate::pcode::{PcodeOperation, PcodeSequence, Varnode};

// ============================================================================
// AnalysisPipeline
// ============================================================================

/// The decompiler analysis pipeline.
///
/// Orchestrates the full decompilation flow from raw P-code sequences
/// (generated by SLEIGH) to structured, type-annotated C output.
///
/// # Pipeline stages
///
/// | Stage | Description |
/// |-------|-------------|
/// | 1. CFG | Build control-flow graph from P-code sequences |
/// | 2. SSA | Convert to static single assignment form |
/// | 3. Data-flow | Reaching definitions, constant propagation, range analysis |
/// | 4. Simplify | Constant folding, algebraic identities, dead code elimination |
/// | 5. Structuring | Control flow structuring (if/else, loops, switch) |
/// | 6. Output | Format as C source code |
#[derive(Debug)]
pub struct AnalysisPipeline {
    /// The input P-code sequences (one per machine instruction).
    pub sequences: Vec<PcodeSequence>,
    /// The constructed control-flow graph.
    pub cfg: Option<cfg::ControlFlowGraph>,
    /// The SSA form of the function.
    pub ssa: Option<ssa::SsaForm>,
    /// Per-varnode constant values discovered during propagation.
    pub constants: HashMap<Varnode, u64>,
    /// Simplified P-code operations.
    pub simplified_ops: Vec<PcodeOperation>,
    /// Pipeline configuration options.
    pub options: PipelineOptions,
}

/// Options controlling the analysis pipeline.
#[derive(Debug, Clone)]
pub struct PipelineOptions {
    /// Enable constant propagation.
    pub constant_propagation: bool,
    /// Enable copy propagation.
    pub copy_propagation: bool,
    /// Enable dead-code elimination.
    pub dead_code_elimination: bool,
    /// Enable expression simplification.
    pub expression_simplification: bool,
    /// Enable range analysis (value-set abstract interpretation).
    pub range_analysis: bool,
    /// Enable type recovery.
    pub type_recovery: bool,
}

impl Default for PipelineOptions {
    fn default() -> Self {
        Self {
            constant_propagation: true,
            copy_propagation: true,
            dead_code_elimination: true,
            expression_simplification: true,
            range_analysis: true,
            type_recovery: true,
        }
    }
}

impl AnalysisPipeline {
    /// Create a new analysis pipeline from P-code sequences.
    pub fn new(sequences: Vec<PcodeSequence>) -> Self {
        Self {
            sequences,
            cfg: None,
            ssa: None,
            constants: HashMap::new(),
            simplified_ops: Vec::new(),
            options: PipelineOptions::default(),
        }
    }

    /// Create a pipeline with custom options.
    pub fn with_options(sequences: Vec<PcodeSequence>, options: PipelineOptions) -> Self {
        Self {
            sequences,
            cfg: None,
            ssa: None,
            constants: HashMap::new(),
            simplified_ops: Vec::new(),
            options,
        }
    }

    // ------------------------------------------------------------------
    // Stage 1: Build CFG
    // ------------------------------------------------------------------

    /// Build the control-flow graph from P-code sequences.
    pub fn build_cfg(&mut self) -> GhidraResult<&cfg::ControlFlowGraph> {
        let cfg = cfg::build_cfg(&self.sequences)?;
        self.cfg = Some(cfg);
        Ok(self.cfg.as_ref().unwrap())
    }

    // ------------------------------------------------------------------
    // Stage 2: Build SSA
    // ------------------------------------------------------------------

    /// Build SSA form from the CFG and P-code operations.
    ///
    /// Requires stage 1 (CFG) to have been completed first.
    pub fn build_ssa(&mut self) -> GhidraResult<&ssa::SsaForm> {
        let cfg = self.cfg.as_ref()
            .ok_or_else(|| ghidra_core::error::GhidraError::InvalidState(
                "CFG must be built before SSA".into()
            ))?;

        // Flatten all operations across all sequences.
        let all_ops: Vec<PcodeOperation> = self.sequences
            .iter()
            .flat_map(|s| s.flatten())
            .collect();

        // Build the dominator tree.
        let dom = ssa::DominatorTree::compute(cfg);

        // Build SSA.
        let builder = ssa::SsaBuilder::new(all_ops, cfg.clone(), dom);
        let ssa_form = builder.build();
        self.ssa = Some(ssa_form);
        Ok(self.ssa.as_ref().unwrap())
    }

    // ------------------------------------------------------------------
    // Stage 3: Data-flow analysis
    // ------------------------------------------------------------------

    /// Run data-flow analysis passes: constant propagation, copy propagation,
    /// range analysis.
    ///
    /// Requires stage 1 (CFG) to have been completed first.
    pub fn run_dataflow(&mut self) -> GhidraResult<()> {
        let _cfg = self.cfg.as_ref()
            .ok_or_else(|| ghidra_core::error::GhidraError::InvalidState(
                "CFG must be built before data-flow analysis".into()
            ))?;

        let all_ops: Vec<PcodeOperation> = self.sequences
            .iter()
            .flat_map(|s| s.flatten())
            .collect();

        // Constant propagation.
        if self.options.constant_propagation {
            let mut cp = dataflow::ConstantPropagation::new();
            self.constants = cp.analyze(&all_ops)
                .into_iter()
                .filter_map(|(vn, cv)| {
                    cv.value().map(|v| (vn, v))
                })
                .collect();
        }

        // Copy propagation.
        if self.options.copy_propagation {
            let mut propagator = dataflow::CopyPropagation::new();
            propagator.propagate(&all_ops, &self.constants);
            // Merge discovered copies back into constants.
            for (dst, src_vn) in propagator.copies() {
                if let Some(&val) = self.constants.get(&src_vn) {
                    self.constants.insert(dst.clone(), val);
                }
            }
        }

        // Range analysis.
        if self.options.range_analysis {
            let mut ra = dataflow::RangeAnalysis::new();
            ra.analyze(&all_ops, &self.constants);
            // Augment constants with range-derived values.
            for (vn, vs) in ra.ranges() {
                if let Some(val) = vs.as_constant() {
                    self.constants.entry(vn.clone()).or_insert(val as u64);
                }
            }
        }

        Ok(())
    }

    // ------------------------------------------------------------------
    // Stage 4: Simplify
    // ------------------------------------------------------------------

    /// Run expression simplification: constant folding, algebraic identities,
    /// dead-code elimination.
    pub fn run_simplification(&mut self) -> GhidraResult<()> {
        let all_ops: Vec<PcodeOperation> = self.sequences
            .iter()
            .flat_map(|s| s.flatten())
            .collect();

        let mut ops = all_ops;

        // Expression simplification.
        if self.options.expression_simplification {
            let simplifier = simplify::ExpressionSimplifier::with_constants(
                self.constants.clone()
            );
            ops = simplifier.simplify(&ops);
        }

        // Dead-code elimination.
        if self.options.dead_code_elimination {
            ops = dataflow::DeadCodeElimination::eliminate(&ops);
        }

        self.simplified_ops = ops;
        Ok(())
    }

    // ------------------------------------------------------------------
    // Run all stages
    // ------------------------------------------------------------------

    /// Run the complete analysis pipeline in order.
    ///
    /// This is the recommended entry point for most callers. It executes
    /// stages 1-4 in sequence and returns the CFG for further processing
    /// (structuring and output generation).
    pub fn run_all(&mut self) -> GhidraResult<&cfg::ControlFlowGraph> {
        self.build_cfg()?;
        self.build_ssa()?;
        self.run_dataflow()?;
        self.run_simplification()?;
        Ok(self.cfg.as_ref().unwrap())
    }

    /// Returns the constructed CFG, if available.
    pub fn cfg(&self) -> Option<&cfg::ControlFlowGraph> {
        self.cfg.as_ref()
    }

    /// Returns the SSA form, if available.
    pub fn ssa(&self) -> Option<&ssa::SsaForm> {
        self.ssa.as_ref()
    }

    /// Returns the discovered constants.
    pub fn constants(&self) -> &HashMap<Varnode, u64> {
        &self.constants
    }

    /// Returns the simplified operations in execution order.
    pub fn simplified_ops(&self) -> &[PcodeOperation] {
        &self.simplified_ops
    }
}

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pcode::opcodes::OpCode;
    use ghidra_core::addr::Address;

    fn test_addr(offset: u64) -> Address {
        Address::new(offset)
    }

    fn make_vn_const(val: u64, size: u32) -> Varnode {
        Varnode::constant(val, size)
    }

    fn make_vn_unique(id: u64, size: u32) -> Varnode {
        Varnode::unique(id, size)
    }

    #[allow(dead_code)]
    fn make_vn_reg(offset: u64, size: u32) -> Varnode {
        Varnode::register("reg", offset, size)
    }

    #[test]
    fn test_pipeline_new() {
        let pipeline = AnalysisPipeline::new(vec![]);
        assert!(pipeline.cfg.is_none());
        assert!(pipeline.ssa.is_none());
        assert!(pipeline.sequences.is_empty());
    }

    #[test]
    fn test_pipeline_with_options() {
        let opts = PipelineOptions {
            constant_propagation: false,
            ..Default::default()
        };
        let pipeline = AnalysisPipeline::with_options(vec![], opts);
        assert!(!pipeline.options.constant_propagation);
    }

    #[test]
    fn test_pipeline_build_cfg_empty() {
        let mut pipeline = AnalysisPipeline::new(vec![]);
        let result = pipeline.build_cfg();
        assert!(result.is_ok());
        let cfg = result.unwrap();
        assert!(cfg.block_count() > 0);
    }

    #[test]
    fn test_pipeline_run_all_linear() {
        let addr = test_addr(0x1000);
        let seq = PcodeSequence::new(
            vec![
                PcodeOperation::new_unannotated(
                    OpCode::INT_ADD,
                    Some(make_vn_unique(0, 4)),
                    vec![make_vn_const(3, 4), make_vn_const(4, 4)],
                ),
                PcodeOperation::new_unannotated(
                    OpCode::RETURN,
                    None,
                    vec![],
                ),
            ],
            addr,
            4,
        );

        let mut pipeline = AnalysisPipeline::new(vec![seq]);
        let result = pipeline.run_all();
        assert!(result.is_ok());
        assert!(pipeline.cfg().is_some());
        assert!(pipeline.ssa().is_some());
        assert!(!pipeline.constants().is_empty() || true); // constants may or may not be found
    }

    #[test]
    fn test_pipeline_stages_in_order() {
        let addr = test_addr(0x1000);
        let seq = PcodeSequence::new(
            vec![
                PcodeOperation::new_unannotated(
                    OpCode::COPY,
                    Some(make_vn_unique(0, 4)),
                    vec![make_vn_const(42, 4)],
                ),
            ],
            addr,
            4,
        );

        let mut pipeline = AnalysisPipeline::new(vec![seq]);
        assert!(pipeline.build_cfg().is_ok());
        assert!(pipeline.build_ssa().is_ok());
        assert!(pipeline.run_dataflow().is_ok());
        assert!(pipeline.run_simplification().is_ok());
    }
}
