//! `FieldFactory` -- base class for listing field factories.
//!
//! Ported from `ghidra.app.util.viewer.field.FieldFactory`.

/// Trait for field factories that generate display fields in the listing.
///
/// Each factory is responsible for creating fields for a specific type of
/// listing data (addresses, mnemonics, operands, comments, etc.).
///
/// Ported from `FieldFactory.java`.
pub trait FieldFactory: std::fmt::Debug {
    /// The name of this field factory.
    fn name(&self) -> &str;

    /// Returns a new instance of this factory for use in a specific format model.
    fn clone_factory(&self) -> Box<dyn FieldFactory>;

    /// Returns true if this factory is enabled for display.
    fn is_enabled(&self) -> bool;

    /// Enable or disable this factory.
    fn set_enabled(&mut self, enabled: bool);

    /// Get the starting X position of fields generated by this factory.
    fn start_x(&self) -> i32;

    /// Set the starting X position.
    fn set_start_x(&mut self, x: i32);

    /// Get the width of fields generated by this factory.
    fn width(&self) -> i32;

    /// Set the width.
    fn set_width(&mut self, width: i32);

    /// Returns true if this factory accepts the given data type for field generation.
    fn accepts(&self, data_type: &str) -> bool;
}

/// Base implementation for common field factory properties.
#[derive(Debug, Clone)]
pub struct BaseFieldFactory {
    name: String,
    enabled: bool,
    start_x: i32,
    width: i32,
}

impl BaseFieldFactory {
    /// Create a new base field factory.
    pub fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            enabled: true,
            start_x: 0,
            width: 100,
        }
    }
}

impl FieldFactory for BaseFieldFactory {
    fn name(&self) -> &str {
        &self.name
    }

    fn clone_factory(&self) -> Box<dyn FieldFactory> {
        Box::new(self.clone())
    }

    fn is_enabled(&self) -> bool {
        self.enabled
    }

    fn set_enabled(&mut self, enabled: bool) {
        self.enabled = enabled;
    }

    fn start_x(&self) -> i32 {
        self.start_x
    }

    fn set_start_x(&mut self, x: i32) {
        self.start_x = x;
    }

    fn width(&self) -> i32 {
        self.width
    }

    fn set_width(&mut self, width: i32) {
        self.width = width;
    }

    fn accepts(&self, _data_type: &str) -> bool {
        true
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_field_factory_properties() {
        let mut f = BaseFieldFactory::new("Address");
        assert_eq!(f.name(), "Address");
        assert!(f.is_enabled());
        assert_eq!(f.start_x(), 0);
        assert_eq!(f.width(), 100);

        f.set_enabled(false);
        assert!(!f.is_enabled());

        f.set_start_x(50);
        assert_eq!(f.start_x(), 50);
    }

    #[test]
    fn test_clone_factory() {
        let f = BaseFieldFactory::new("Mnemonic");
        let f2 = f.clone_factory();
        assert_eq!(f2.name(), "Mnemonic");
    }
}
