//! PE (Portable Executable) format types ported from Ghidra's
//! `ghidra.app.util.bin.format.pe` package.
//!
//! Provides:
//! - [`pe_constants`] -- PE constants, machine types, data directory indices,
//!   and machine name/processor resolution utilities
//! - [`pe_dll_characteristics`] -- DLL characteristic flags and bitfield helper
//! - [`pe_section_flags`] -- section characteristic flags, bitfield helper,
//!   and PE subsystem enumeration

pub mod pe_constants;
pub mod pe_data_directory;
pub mod pe_dll_characteristics;
pub mod pe_file_header;
pub mod pe_import_thunks;
pub mod pe_nt_header;
pub mod pe_optional_header;
pub mod pe_section_flags;
pub mod pe_section_header;

pub use pe_constants::{
    data_directory_name, is_32bit_machine, is_64bit_machine, machine_bit_size,
    machine_to_processor, machine_type_name, IMAGE_ARCHIVE_END, IMAGE_ARCHIVE_LINKER_MEMBER,
    IMAGE_ARCHIVE_LONGNAMES_MEMBER, IMAGE_ARCHIVE_PAD, IMAGE_ARCHIVE_START,
    IMAGE_ARCHIVE_START_SIZE, IMAGE_DIRECTORY_ENTRY_ARCHITECTURE,
    IMAGE_DIRECTORY_ENTRY_BASERELOC, IMAGE_DIRECTORY_ENTRY_BOUND_IMPORT,
    IMAGE_DIRECTORY_ENTRY_COM_DESCRIPTOR, IMAGE_DIRECTORY_ENTRY_DEBUG,
    IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT, IMAGE_DIRECTORY_ENTRY_EXCEPTION,
    IMAGE_DIRECTORY_ENTRY_EXPORT, IMAGE_DIRECTORY_ENTRY_GLOBALPTR, IMAGE_DIRECTORY_ENTRY_IAT,
    IMAGE_DIRECTORY_ENTRY_IMPORT, IMAGE_DIRECTORY_ENTRY_LOAD_CONFIG,
    IMAGE_DIRECTORY_ENTRY_RESOURCE, IMAGE_DIRECTORY_ENTRY_SECURITY,
    IMAGE_DIRECTORY_ENTRY_TLS, IMAGE_DOS_HEADER_SIZE, IMAGE_DOS_SIGNATURE,
    IMAGE_FILE_AGGRESIVE_WS_TRIM, IMAGE_FILE_32BIT_MACHINE,
    IMAGE_FILE_BYTES_REVERSED_HI, IMAGE_FILE_BYTES_REVERSED_LO,
    IMAGE_FILE_DEBUG_STRIPPED, IMAGE_FILE_DLL, IMAGE_FILE_EXECUTABLE_IMAGE,
    IMAGE_FILE_HEADER_SIZE, IMAGE_FILE_LARGE_ADDRESS_AWARE,
    IMAGE_FILE_LINE_NUMS_STRIPPED, IMAGE_FILE_LOCAL_SYMS_STRIPPED,
    IMAGE_FILE_MACHINE_ALPHA, IMAGE_FILE_MACHINE_ALPHA64, IMAGE_FILE_MACHINE_AMD64,
    IMAGE_FILE_MACHINE_AM33, IMAGE_FILE_MACHINE_ARM, IMAGE_FILE_MACHINE_ARM64,
    IMAGE_FILE_MACHINE_ARMNT, IMAGE_FILE_MACHINE_AXP64, IMAGE_FILE_MACHINE_CEE,
    IMAGE_FILE_MACHINE_CEF, IMAGE_FILE_MACHINE_EBC, IMAGE_FILE_MACHINE_I386,
    IMAGE_FILE_MACHINE_IA64, IMAGE_FILE_MACHINE_M32R, IMAGE_FILE_MACHINE_MIPS16,
    IMAGE_FILE_MACHINE_MIPSFPU, IMAGE_FILE_MACHINE_MIPSFPU16,
    IMAGE_FILE_MACHINE_POWERPC, IMAGE_FILE_MACHINE_POWERPCFP,
    IMAGE_FILE_MACHINE_R10000, IMAGE_FILE_MACHINE_R3000, IMAGE_FILE_MACHINE_R4000,
    IMAGE_FILE_MACHINE_SH3, IMAGE_FILE_MACHINE_SH3DSP, IMAGE_FILE_MACHINE_SH3E,
    IMAGE_FILE_MACHINE_SH4, IMAGE_FILE_MACHINE_SH5, IMAGE_FILE_MACHINE_THUMB,
    IMAGE_FILE_MACHINE_TRICORE, IMAGE_FILE_MACHINE_UNKNOWN,
    IMAGE_FILE_MACHINE_WCEMIPSV2, IMAGE_FILE_NET_RUN_FROM_SWAP,
    IMAGE_FILE_RELOCS_STRIPPED, IMAGE_FILE_REMOVABLE_RUN_FROM_SWAP,
    IMAGE_FILE_SYSTEM, IMAGE_FILE_UP_SYSTEM_ONLY, IMAGE_NUMBEROF_DIRECTORY_ENTRIES,
    IMAGE_NT_OPTIONAL_HDR32_MAGIC, IMAGE_NT_OPTIONAL_HDR64_MAGIC, IMAGE_NT_SIGNATURE,
    IMAGE_ORDINAL_FLAG32, IMAGE_ORDINAL_FLAG64, IMAGE_OS2_SIGNATURE,
    IMAGE_OS2_SIGNATURE_LE, IMAGE_ROM_OPTIONAL_HDR_MAGIC,
    IMAGE_SIZEOF_NT_OPTIONAL32_HEADER, IMAGE_SIZEOF_NT_OPTIONAL64_HEADER,
    IMAGE_SIZEOF_ROM_OPTIONAL_HEADER, IMAGE_SIZEOF_SECTION_HEADER,
    IMAGE_SIZEOF_SHORT_NAME, IMAGE_SIZEOF_STD_OPTIONAL_HEADER,
    IMAGE_VXD_SIGNATURE, RICH_MAGIC, RICH_SIGNATURE,
};
pub use pe_dll_characteristics::{DllCharacteristic, DllCharacteristics};
pub use pe_section_flags::{PeSubsystem, SectionCharacteristics, SectionFlag};
